// <auto-generated />
namespace ArtGallery.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class Lyuboe : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Lyuboe));
        
        string IMigrationMetadata.Id
        {
            get { return "202003060412561_Lyuboe"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
