// <auto-generated />
namespace ArtGallery.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class gg3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(gg3));
        
        string IMigrationMetadata.Id
        {
            get { return "202006051644291_gg3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
