// <auto-generated />
namespace ArtGallery.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class migr : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(migr));
        
        string IMigrationMetadata.Id
        {
            get { return "202003260259479_migr"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
